name: "Generate Tag"
description: "Generate Tag for Docker Image"
inputs:
  tag:
    description: "Tag of the Docker images to attach to the environment"
    required: false
  length:
    description: "Length of the shortened commit SHA"
    default: "7"
    required: true
  prefix:
    description: "Prefix for the tag"
    default: ""
    required: false
outputs:
  tag:
    description: "Docker image Tag"
runs:
  using: "node20"
  main: "../../dist/generate-tag/index.js"
