name: "aws eks"
description: "Update kubeconfig for aws eks"
inputs:
  cluster-name:
    description: "EKS cluster name"
    required: true
  aws-region:
    description: "AWS region"
    required: false
    default: "ap-northeast-2"
  role-to-assume:
    description: "Role to assume"
    required: true
  role-session-name:
    description: "Role session name"
    required: false
    default: "github-actions"
  helm-path:
    description: "Helm path"
    required: false
    default: ""
  deploy-name:
    description: "Deploy name"
    required: false
    default: ""
  values-name:
    description: "Values name"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Update KubeConfig
      shell: bash
      run: |
        aws eks update-kubeconfig \
          --name ${{ inputs.cluster-name }} \
          --region ${{ inputs.aws-region }}

        # 검증
        kubectl config current-context
    - name: Install Helm Client
      uses: azure/setup-helm@v3
      if: ${{ inputs.helm-path != '' }}
      with:
        version: v3.8.2

    - name: Helm install
      if: ${{ inputs.helm-path != '' }}
      shell: bash
      run: |
        helm upgrade --install -f .helm/${{ inputs.values-name }} \
          --set images.tag=${{ needs.build.outputs.tag }} \
          ${{ inputs.deploy-name }} .helm
