name: "aws eks"
description: "Update kubeconfig for aws eks"
inputs:
  cluster-name:
    description: "EKS cluster name"
    required: true
  aws-region:
    description: "AWS region"
    required: false
    default: "ap-northeast-2"
  role-to-assume:
    description: "Role to assume"
    required: true
  role-session-name:
    description: "Role session name"
    required: false
    default: "github-actions"

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Update KubeConfig
      shell: bash
      run: |
        aws eks update-kubeconfig \
          --name ${{ inputs.cluster-name }} \
          --region ${{ inputs.aws-region }}

        # 검증
        kubectl config current-context
